name: ${project.name}
main: com.michaelelin.WGUseFlags.WGUseFlagsPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: false
depend: [WorldGuard, WGCustomFlags]
authors: [Dumbo52]
